---
name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0/3 * * *"
concurrency: renovate
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
      - name: Validate Renovate JSON
        run: jq type .github/renovate.json
      - name: Install cli tools
        run: |
          uv tool install pre-commit
          uv tool install poetry
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@9fea9f0fbf80401026d11d03911d62b1f70fef1f # v46.3.3
        with:
          configurationFile: .github/renovate-global.json
          token: ${{ secrets.RENOVATE_TOKEN }}
